application: miraclestyle-development
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:    
- url: /.*
  script: app.wsgi.app
  
libraries:
 
- name: django
  version: "1.5"

- name: PIL
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'app.settings'
  
builtins:
- appstats: on
